steps:
  # Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args: 
      - 'build'
      - '-t'
      - '${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPOSITORY}/${_IMAGE}:${COMMIT_SHA}'
      - '-t'
      - '${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPOSITORY}/${_IMAGE}:latest'
      - '.'

  # Push the container image to Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - '--all-tags'
      - '${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPOSITORY}/${_IMAGE}'

  # Deploy container image to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - '${_SERVICE_NAME}'
      - '--image'
      - '${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPOSITORY}/${_IMAGE}:${COMMIT_SHA}'
      - '--region'
      - '${_REGION}'
      - '--platform'
      - 'managed'
      - '--service-account'
      - '${_SERVICE_NAME}@${PROJECT_ID}.iam.gserviceaccount.com'
      - '--set-secrets'
      - 'OPENAI_API_KEY=OPENAI_API_KEY:latest,APP_URL=APP_URL:latest,LEMON_SQUEEZY_STORE_ID=LEMON_SQUEEZY_STORE_ID:latest,LEMON_SQUEEZY_VARIANT_ID=LEMON_SQUEEZY_VARIANT_ID:latest,LEMON_SQUEEZY_VARIANT_ID_BUNDLE=LEMON_SQUEEZY_VARIANT_ID_BUNDLE:latest,LEMON_API_KEY=LEMON_API_KEY:latest,LEMON_SQUEEZY_WEBHOOK_SECRET=LEMON_SQUEEZY_WEBHOOK_SECRET:latest,ADMIN_API_KEY=ADMIN_API_KEY:latest,CSRF_SECRET=CSRF_SECRET:latest'
      - '--set-env-vars'
      - 'NODE_ENV=production,DATA_STORAGE_TYPE=cloud-storage,STORAGE_BUCKET=cv-opt-user-data'
      - '--memory'
      - '512Mi'
      - '--cpu'
      - '1'
      - '--timeout'
      - '900'
      - '--concurrency'
      - '80'
      - '--max-instances'
      - '10'

images:
  - '${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPOSITORY}/${_IMAGE}:${COMMIT_SHA}'
  - '${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPOSITORY}/${_IMAGE}:latest'

substitutions:
  _REGION: us-east1
  _REPOSITORY: cv-opt-repo
  _IMAGE: cv-opt
  _SERVICE_NAME: cv-opt

options:
  logging: CLOUD_LOGGING_ONLY
  substitution_option: 'ALLOW_LOOSE'